### ISSUE TITLE
Resource Leaking

### ISSUE THREAD

**Issue by Zard-C** [truehang/lite_tcp#1]
https://github.com/truehang/lite_tcp/blame/939d375ea4e0316bd4382ae5bd65f55a1f048945/src/lite_tcp.cpp#L295
Need ` close(fd_)` in distructor.

**Comment by truehang** [comment]
Thanks for your kindly reminder. Acctually, I did that in destructor of LiteTcpClient.

**Comment by truehang** [comment]
`LiteTcpClient::~LiteTcpClient()
{
  if (run_ || stop_) {
    process_thread_.join();
  }
  close(sockfd_);
}`
You means this file descriptor? I have did that.
